import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/hero'
import Teaser from '../components/teaser'
import styles from '../styles/Home.module.css'
import Script from 'next/script'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Home - Hunter Stubbs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="https://i.imgur.com/Fp3hUY0.png" />
      </Head>
      <body>
      <Hero />
      </body>
    </div>
  )
}
